#!/usr/bin/env python
# coding: utf-8

"Simple application launcher."

def main():
    import os
    import sys
    try:
        import crispy
    except ImportError:
        # The package is run without being installed; its path must be first 
        # added to sys.path.
        _dir = os.path.join(os.path.dirname(__file__), '../..')
        sys.path.insert(0, os.path.abspath(_dir))
        import crispy

    crispy.gui.canvas.main()

if __name__ == '__main__':
    main()
