#!/usr/bin/env python
# coding: utf-8

"""A simple launcher."""

def main():
    import os
    import sys
    import crispy

    print(os.path.dirname(crispy.__file__))

if __name__ == '__main__':
    main()
