#!/usr/bin/env python
# coding: utf-8


def main():
    """Simple application launcher."""
    import os
    import sys
    try:
        from crispy.__main__ import main
    except ImportError:
        # The package is run without being installed; its path must be first 
        # added to sys.path.
        _dir = os.path.join(os.path.dirname(__file__), '..')
        sys.path.insert(0, os.path.abspath(_dir))
        from crispy.__main__ import main

    main()

if __name__ == '__main__':
    main()
