name: continuous-integration

on:
  pull_request:
  push:
    branches:
      - main
  release:

jobs:
  check-style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install .[devel]

      - name: Check style
        run: |
          ruff format --check .

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install system packages
        run: |
          sudo apt -y install libegl1

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install .[devel]
          pip list
          
      - name: Run tests
        run: |
          pytest

  build-binaries:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 6
      fail-fast: false
      matrix:
        os: [ macos-13, macos-14, windows-2019 ]
        python-version: ["3.12",]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install packaging dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[devel]

      - name: Install Inno Setup
        if: runner.os == 'Windows'
        run: |
          choco install innosetup

      - name: Run PyInstaller
        run: |
          cd package
          pyinstaller --noconfirm crispy.spec
          cd ..

      - name: Recursively list folder
        run: |
          ls -R

      - name: Get version
        id: crispy_version
        run: |
            echo "VERSION=$(python -c 'from crispy import __version__; print(__version__)')" >> $GITHUB_ENV

      - name: Get the architecture 
        id: architecture
        run: |
            echo "ARCH=$(python -c 'import platform; print(platform.machine().lower()')" >> $GITHUB_ENV

      - name: Upload the Windows installer
        uses: actions/upload-artifact@v4
        if: runner.os == 'Windows'
        with:
          name: Crispy-${{ env.VERSION }}-${{ env.ARCH }}
          path: package\artifacts\*.exe

      - name: Upload the macOS app
        uses: actions/upload-artifact@v4
        if: runner.os == 'macOS'
        with:
          name: Crispy-${{ env.VERSION }}-${{ env.ARCH }}
          path: package/artifacts/*.dmg
